LIST_OF_MATIRIAL = ['нефть', 'бензин']
LIST_OF_COST_OF_MATERIAL = [100, 200]
DICT_OF_COST_OF_MATERIAL = dict()
for i in range(len(LIST_OF_MATIRIAL)):
    DICT_OF_COST_OF_MATERIAL[LIST_OF_MATIRIAL[i]] = LIST_OF_COST_OF_MATERIAL[i]
